import './globals.css'
import styles from './page.module.css'
import SearchInput from './components/SearchInput'


export const metadata = {
  title: 'Search example with Next 13.2',
  description: 'Generated by create next app',
}

import { Signika } from 'next/font/google';
import Link from 'next/link';
import Providers from './components/Providers';
import UserActions from './components/UserActions';

const signika = Signika({ subsets: ['latin'] });


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={signika.className}>
        <div className={styles.container}>
          <Providers>
            <header className={styles.mainHeader}>
              <Link className={styles.homeButton} href="/">Home</Link>
              <SearchInput />
              <UserActions />
            </header>
            <div className={styles.mainContainer}>
              {children}
            </div>
          </Providers>
        </div>
      </body>
    </html >
  )
}
